import { createClient } from '@supabase/supabase-js';
import nodemailer from 'nodemailer';

interface AchievementAutomationRequest {
  achievementId: number;
  studentLrn: string;
}

function formatDisplayDate(raw: string | null | undefined): string {
  if (!raw) return 'N/A';
  const d = new Date(raw);
  if (Number.isNaN(d.getTime())) return raw;
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

function formatDisplayTime(raw: string | null | undefined): string {
  if (!raw) return 'N/A';
  const normalized = raw.replace(/\./g, ':');
  const [h, m] = normalized.split(':').map(Number);
  if (Number.isNaN(h) || Number.isNaN(m)) return raw;
  const suffix = h >= 12 ? 'PM' : 'AM';
  const hour12 = h % 12 || 12;
  return `${hour12}:${String(m).padStart(2, '0')} ${suffix}`;
}

function buildAchievementEmailContent(payload: {
  schoolName: string;
  parentName: string;
  studentName: string;
  level: string;
  achievementType: string;
  description: string;
  notes?: string | null;
  date: string;
  time: string;
  reportedBy: string;
}) {
  const subject = `[${payload.schoolName}] Achievement Update for ${payload.studentName}`;

  const text = [
    `Dear ${payload.parentName},`,
    '',
    `We are pleased to share a positive achievement update for your child, ${payload.studentName}.`,
    '',
    'ACHIEVEMENT DETAILS',
    '-----------------------------------',
    `Student        : ${payload.studentName}`,
    `Level          : ${payload.level || 'N/A'}`,
    `Achievement    : ${payload.achievementType}`,
    `Description    : ${payload.description}`,
    `Date           : ${payload.date}`,
    `Time           : ${payload.time}`,
    `Reported By    : ${payload.reportedBy}`,
    payload.notes ? `Additional Notes: ${payload.notes}` : '',
    '',
    'Thank you for your continued partnership and support.',
    '',
    `Respectfully,`,
    `The ${payload.schoolName} Administration`,
    '',
    '-----------------------------------',
    'This is an automated notification generated by the SafeGate Student Monitoring System.',
    'Please do not reply directly to this email.',
  ]
    .filter(Boolean)
    .join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0" />
  <title>${subject}</title>
</head>
<body style="margin:0;padding:0;background-color:#f8fafc;font-family:'Segoe UI',Arial,sans-serif;color:#1e293b;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:32px 16px;">
    <tr>
      <td align="center">
        <table width="620" cellpadding="0" cellspacing="0" style="max-width:620px;width:100%;">
          <tr>
            <td style="background:linear-gradient(135deg,#1e3a5f 0%,#ff8a00 100%);border-radius:12px 12px 0 0;padding:32px 36px;">
              <p style="margin:0;color:#fed7aa;font-size:12px;letter-spacing:1.5px;text-transform:uppercase;font-weight:600;">${payload.schoolName} Student Monitoring System</p>
              <h1 style="margin:8px 0 0;color:#ffffff;font-size:22px;font-weight:700;line-height:1.3;">Student Achievement Update</h1>
            </td>
          </tr>
          <tr>
            <td style="background:#ffffff;padding:36px;border-left:1px solid #e2e8f0;border-right:1px solid #e2e8f0;">
              <p style="margin:0 0 8px;font-size:15px;color:#374151;">Dear <strong>${payload.parentName}</strong>,</p>
              <p style="margin:0 0 20px;font-size:15px;color:#374151;line-height:1.7;">
                We are happy to share a positive recognition for <strong>${payload.studentName}</strong>.
                Thank you for your continued support in your child's growth.
              </p>

              <h2 style="margin:0 0 14px;font-size:15px;font-weight:700;color:#1e293b;text-transform:uppercase;letter-spacing:0.8px;">Achievement Details</h2>
              <table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;margin-bottom:24px;">
                <tr style="background:#fff7ed;">
                  <td style="padding:11px 16px;border-bottom:1px solid #e2e8f0;width:38%;"><span style="font-size:13px;font-weight:600;color:#9a3412;text-transform:uppercase;letter-spacing:0.5px;">Student</span></td>
                  <td style="padding:11px 16px;border-bottom:1px solid #e2e8f0;"><span style="font-size:14px;color:#1e293b;font-weight:600;">${payload.studentName}</span></td>
                </tr>
                <tr>
                  <td style="padding:11px 16px;border-bottom:1px solid #e2e8f0;background:#fff7ed;"><span style="font-size:13px;font-weight:600;color:#9a3412;text-transform:uppercase;letter-spacing:0.5px;">Level</span></td>
                  <td style="padding:11px 16px;border-bottom:1px solid #e2e8f0;"><span style="font-size:14px;color:#1e293b;">${payload.level || 'N/A'}</span></td>
                </tr>
                <tr style="background:#fff7ed;">
                  <td style="padding:11px 16px;border-bottom:1px solid #e2e8f0;"><span style="font-size:13px;font-weight:600;color:#9a3412;text-transform:uppercase;letter-spacing:0.5px;">Achievement</span></td>
                  <td style="padding:11px 16px;border-bottom:1px solid #e2e8f0;"><span style="font-size:14px;color:#1e293b;">${payload.achievementType}</span></td>
                </tr>
                <tr>
                  <td style="padding:11px 16px;border-bottom:1px solid #e2e8f0;background:#fff7ed;"><span style="font-size:13px;font-weight:600;color:#9a3412;text-transform:uppercase;letter-spacing:0.5px;">Date</span></td>
                  <td style="padding:11px 16px;border-bottom:1px solid #e2e8f0;"><span style="font-size:14px;color:#1e293b;">${payload.date}</span></td>
                </tr>
                <tr style="background:#fff7ed;">
                  <td style="padding:11px 16px;border-bottom:1px solid #e2e8f0;"><span style="font-size:13px;font-weight:600;color:#9a3412;text-transform:uppercase;letter-spacing:0.5px;">Time</span></td>
                  <td style="padding:11px 16px;border-bottom:1px solid #e2e8f0;"><span style="font-size:14px;color:#1e293b;">${payload.time}</span></td>
                </tr>
                <tr>
                  <td style="padding:11px 16px;border-bottom:1px solid #e2e8f0;background:#fff7ed;"><span style="font-size:13px;font-weight:600;color:#9a3412;text-transform:uppercase;letter-spacing:0.5px;">Description</span></td>
                  <td style="padding:11px 16px;border-bottom:1px solid #e2e8f0;"><span style="font-size:14px;color:#1e293b;">${payload.description}</span></td>
                </tr>
                <tr style="background:#fff7ed;">
                  <td style="padding:11px 16px;"><span style="font-size:13px;font-weight:600;color:#9a3412;text-transform:uppercase;letter-spacing:0.5px;">Reported By</span></td>
                  <td style="padding:11px 16px;"><span style="font-size:14px;color:#1e293b;">${payload.reportedBy}</span></td>
                </tr>
              </table>

              ${payload.notes ? `<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:14px 16px;margin-bottom:24px;"><p style="margin:0 0 6px;font-size:12px;font-weight:700;color:#475569;text-transform:uppercase;letter-spacing:.5px;">Additional Notes</p><p style="margin:0;font-size:14px;color:#334155;line-height:1.7;white-space:pre-line;">${payload.notes}</p></div>` : ''}

              <p style="margin:0 0 6px;font-size:14px;color:#374151;line-height:1.7;">
                We appreciate your partnership in nurturing your child's strengths and positive behavior.
              </p>
              <p style="margin:20px 0 0;font-size:14px;color:#374151;">Respectfully,</p>
              <p style="margin:4px 0 0;font-size:14px;font-weight:700;color:#1e293b;">The ${payload.schoolName} Administration</p>
            </td>
          </tr>
          <tr>
            <td style="background:#1e293b;border-radius:0 0 12px 12px;padding:20px 36px;text-align:center;">
              <p style="margin:0;font-size:12px;color:#94a3b8;line-height:1.6;">
                This is an automated notification from the <strong style="color:#cbd5e1;">${payload.schoolName}</strong> Student Monitoring System.<br />
                Please do not reply directly to this email. Contact the school office for inquiries.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

  return { subject, text, html };
}

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as Partial<AchievementAutomationRequest>;
    const achievementId = Number(body.achievementId);
    const studentLrn = body.studentLrn?.trim();

    if (!studentLrn || Number.isNaN(achievementId)) {
      return Response.json(
        {
          success: false,
          error: 'achievementId and studentLrn are required',
        },
        { status: 400 }
      );
    }

    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

    if (!supabaseUrl || !supabaseKey) {
      return Response.json(
        {
          success: false,
          error: 'Missing Supabase credentials',
        },
        { status: 500 }
      );
    }

    const supabase = createClient(supabaseUrl, supabaseKey);

    const { data: student, error: studentError } = await supabase
      .from('students')
      .select('lrn, name, level, parent_name, parent_contact, parent_email')
      .eq('lrn', studentLrn)
      .single();

    if (studentError || !student) {
      return Response.json(
        {
          success: false,
          error: 'Student not found',
          detail: studentError?.message,
        },
        { status: 404 }
      );
    }

    const { data: achievement, error: achievementError } = await supabase
      .from('achievements')
      .select('id, achievement_type, description, notes, reported_by, achievement_date, achievement_time')
      .eq('id', achievementId)
      .single();

    if (achievementError || !achievement) {
      return Response.json(
        {
          success: false,
          error: 'Achievement record not found',
          detail: achievementError?.message,
        },
        { status: 404 }
      );
    }

    const parentContact = student.parent_contact || '';
    const parentEmail = student.parent_email || (parentContact.includes('@') ? parentContact : null);

    if (!parentEmail) {
      return Response.json({
        success: true,
        queued: false,
        message: 'Achievement saved, but no parent email address is available.',
      });
    }

    const smtpHost = process.env.GMAIL_SMTP_HOST || 'smtp.gmail.com';
    const smtpPort = Number(process.env.GMAIL_SMTP_PORT || 465);
    const smtpSecure = (process.env.GMAIL_SMTP_SECURE || 'true').toLowerCase() === 'true';
    const smtpUser = process.env.GMAIL_SMTP_USER;
    const smtpPass = process.env.GMAIL_SMTP_APP_PASSWORD;
    const fromEmail = process.env.GMAIL_FROM_EMAIL || smtpUser;

    if (!smtpUser || !smtpPass || !fromEmail) {
      return Response.json(
        {
          success: false,
          error: 'Missing Gmail SMTP configuration',
          detail: 'Set GMAIL_SMTP_USER, GMAIL_SMTP_APP_PASSWORD, and optional GMAIL_FROM_EMAIL in environment variables.',
        },
        { status: 500 }
      );
    }

    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpSecure,
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    });

    const content = buildAchievementEmailContent({
      schoolName: process.env.SCHOOL_NAME || 'SafeGate',
      parentName: student.parent_name || 'Parent/Guardian',
      studentName: student.name || student.lrn,
      level: student.level || 'N/A',
      achievementType: achievement.achievement_type,
      description: achievement.description,
      notes: achievement.notes,
      date: formatDisplayDate(achievement.achievement_date),
      time: formatDisplayTime(achievement.achievement_time),
      reportedBy: achievement.reported_by || 'School Staff',
    });

    const emailResult = await transporter.sendMail({
      from: fromEmail,
      to: parentEmail,
      subject: content.subject,
      text: content.text,
      html: content.html,
    });

    return Response.json({
      success: true,
      queued: true,
      message: 'Achievement email sent successfully via Gmail SMTP.',
      data: {
        achievementId,
        studentLrn,
        emailMessageId: emailResult.messageId,
      },
    });
  } catch (error) {
    console.error('Achievement automation API error:', error);
    return Response.json(
      {
        success: false,
        error: 'Failed to run achievement automation',
        detail: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
